using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
using TouchLess_Answer;

namespace TouchLess_Answer.App_Code
{
    // <auto-generated />
    //

    //
    //    using TouchLess;
    //
    //    var activty = Activty.FromJson(jsonString);

    namespace TouchLess
    {
        using System;
        using System.Collections.Generic;

        using System.Globalization;
        using Newtonsoft.Json;
        using Newtonsoft.Json.Converters;

        public partial class Activty
        {
            [JsonProperty("The102123", Required = Required.Always)]
            public The10212 The102123 { get; set; }

            [JsonProperty("The102124", Required = Required.Always)]
            public The10212 The102124 { get; set; }

            [JsonProperty("The102125", Required = Required.Always)]
            public The102125 The102125 { get; set; }
        }

        public partial class The10212
        {
            [JsonProperty("Type", Required = Required.Always)]
            public string Type { get; set; }

            [JsonProperty("OUTAgentMACID", Required = Required.Always)]
            public string OutAgentMacid { get; set; }

            [JsonProperty("PlateNumber", Required = Required.Always)]
            public PlateNumber PlateNumber { get; set; }
        }

        public partial class PlateNumber
        {
            [JsonProperty("Image", Required = Required.Always)]
            public string Image { get; set; }

            [JsonProperty("Number", Required = Required.Always)]
            public string Number { get; set; }

            [JsonProperty("TimeStamp", Required = Required.Always)]
            public long TimeStamp { get; set; }
        }

        public partial class The102125
        {
            [JsonProperty("Type", Required = Required.Always)]
            public string Type { get; set; }

            [JsonProperty("INAgentMACID", Required = Required.Always)]
            public string InAgentMacid { get; set; }

            [JsonProperty("PlateNumber", Required = Required.Always)]
            public PlateNumber PlateNumber { get; set; }
        }

        public partial class Activty
        {
            public static Activty FromJson(string json) => JsonConvert.DeserializeObject<Activty>(json, TouchLess.Converter.Settings);
        }

        public static class Serialize
        {
            public static string ToJson(this Activty self) => JsonConvert.SerializeObject(self, TouchLess.Converter.Settings);
        }

        internal static class Converter
        {
            public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
            {
                MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
                DateParseHandling = DateParseHandling.None,
                Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
            };
        }
    }




}